correct style
89219339769/java-explore-with-me pull request #1
Opened 2023-02-13 15:35 UTC by 89219339769

2023-02-15 12:19 UTC, sergeymamonov requested changes
Файлы мавена, файл гитигнор - все это нужно в одном экземпляре на весь проект, и должно находиться в корне проекта. Докерфайлы нужны только там, где мы будем запускать какой-то микросервис. Если тесты писать не планируется, то папку с тестами лучше удалить.

2023-02-15 12:19 UTC, sergeymamonov commented on stat-server/.gitignore
> +HELP.md
Не нужно делать несколько гитигнор файлов. Этот файл должен быть один в корне проекта. У вас один гит репозиторий и гитигнор нужен тоже только один.

2023-02-15 12:19 UTC, sergeymamonov commented on stat-server/Dockerfile
> +FROM amazoncorretto:11
Аналогично. Этот файл нужен только там, где мы будет запускать какое-то приложение. Здесь не нужен.

2023-02-15 12:19 UTC, sergeymamonov commented on stat-server/src/main/java/com/example/statserver/config/Config.java
> +//package com.example.statserver.config;
Никакого закомментированного кода в проекте.

2023-02-15 12:19 UTC, sergeymamonov commented on stat-server/src/main/java/com/example/statserver/model/EndpointHitDto.java
> +public class EndpointHitDto {
Этот класс где-то используется?

2023-02-15 12:19 UTC, sergeymamonov commented on stat-server/src/main/java/com/example/statserver/model/StatMapping.java
> +public class StatMapping {
Этот класс где-то используется?

2023-02-15 12:19 UTC, sergeymamonov commented on stat-server/src/main/java/com/example/statserver/service/StatRepository.java
> +
Зачем эта лишняя пустая строка? Код должен быть опрятным.

2023-02-15 12:19 UTC, sergeymamonov commented on stat-server/src/main/java/com/example/statserver/service/StatRepository.java
> +    List<EndpointHit> findHitCountByUri(LocalDateTime start, LocalDateTime end);
Не вижу, чтобы этот метод где-то использовался бы.

2023-02-15 12:19 UTC, sergeymamonov commented on stat-server/src/main/java/com/example/statserver/service/StatServiceImpl.java
> +    public List<ViewStats> getUniqIpStat(LocalDateTime startDate, LocalDateTime endDate, List<String> uris) {
Метод можно сделать приватным, так как используется только в этом классе.

2023-02-15 12:19 UTC, sergeymamonov commented on stat-server/src/main/java/com/example/statserver/service/StatServiceImpl.java
> +    public List<ViewStats> getAllIpStat(LocalDateTime startDate, LocalDateTime endDate, List<String> uris) {
Метод можно сделать приватным, так как используется только в этом классе.

2023-02-15 12:19 UTC, sergeymamonov commented on stat-server/src/main/java/com/example/statserver/service/StatServiceImpl.java
> +    public List<ViewStats> sortAndFind(List<ViewStats> viewStatsSort, List<String> uris) {
Метод можно сделать приватным, так как используется только в этом классе.

2023-02-15 12:19 UTC, sergeymamonov commented on stat-server/src/main/java/com/example/statserver/service/StatServiceImpl.java
> +            int hitCount = listWithoutDuplicates.size();
А почему бы сразу не определить размер множества? Без перевода в массив.

2023-02-15 12:23 UTC, sergeymamonov requested changes
Модуль статистики должен состоять из трех подмодулей. Посмотрите описание и схему в ТЗ. У каждого подмодуля свой помник. А родительским для этих помников будет помник всего модуля статистики.

2023-02-15 14:39 UTC, 89219339769 commented on stat-server/Dockerfile
> +FROM amazoncorretto:11
Добрый день.  При удалении этого файла приложение не проходит проверку на гитхабе

2023-02-15 14:46 UTC, 89219339769 commented on stat-server/src/main/java/com/example/statserver/service/StatServiceImpl.java
> +            int hitCount = listWithoutDuplicates.size();
Использую  HashSet что бы убрать повторяющиеся Ip

2023-02-15 18:25 UTC, 89219339769 commented on stat-server/.gitignore
> +HELP.md
+

2023-02-15 18:25 UTC, 89219339769 commented on stat-server/src/main/java/com/example/statserver/config/Config.java
> +//package com.example.statserver.config;
+

2023-02-15 18:25 UTC, 89219339769 commented on stat-server/src/main/java/com/example/statserver/model/EndpointHitDto.java
> +public class EndpointHitDto {
удалил

2023-02-15 18:25 UTC, 89219339769 commented on stat-server/src/main/java/com/example/statserver/model/StatMapping.java
> +public class StatMapping {
удалил

2023-02-15 18:25 UTC, 89219339769 commented on stat-server/src/main/java/com/example/statserver/service/StatRepository.java
> +    List<EndpointHit> findHitCountByUri(LocalDateTime start, LocalDateTime end);
удалил

2023-02-15 18:26 UTC, 89219339769 commented on stat-server/src/main/java/com/example/statserver/service/StatServiceImpl.java
> +    public List<ViewStats> getUniqIpStat(LocalDateTime startDate, LocalDateTime endDate, List<String> uris) {
исправил

2023-02-15 18:26 UTC, 89219339769 commented on stat-server/src/main/java/com/example/statserver/service/StatServiceImpl.java
> +    public List<ViewStats> getAllIpStat(LocalDateTime startDate, LocalDateTime endDate, List<String> uris) {
исправил

2023-02-15 18:26 UTC, 89219339769 commented on stat-server/src/main/java/com/example/statserver/service/StatServiceImpl.java
> +    public List<ViewStats> sortAndFind(List<ViewStats> viewStatsSort, List<String> uris) {
исправил

2023-02-16 03:34 UTC, sergeymamonov commented on db/stat.trace.db
> +2023-02-13 15:34:41 jdbc[3]: exception
Зачем вся эта папка в репозитории? Если она не нужна, добавьте ее в гитигнор и удалите из репозитория.

2023-02-16 03:34 UTC, sergeymamonov commented on main-server/.mvn/wrapper/maven-wrapper.properties
> +distributionUrl=https://repo.maven.apache.org/maven2/org/apache/maven/apache-maven/3.8.6/apache-maven-3.8.6-bin.zip
Враппер должен быть в корне проекта, но не здесь.

2023-02-16 03:34 UTC, sergeymamonov commented on stat-server/client/pom.xml
> +        <groupId>org.springframework.boot</groupId>
Родительским помником здесь должен быть stats_server.

2023-02-16 03:34 UTC, sergeymamonov commented on stat-server/client/src/main/java/com/example/client/ClientApplication.java
> +public class ClientApplication {
А где сам клиент? Для клиента не нужен класс с методом main. В клиенте ничего запускаться не будет. Но нужен сам код клиента, через который мы будем обращаться к микросервису со статистикой.

2023-02-16 03:34 UTC, sergeymamonov commented on stat-server/Dockerfile
> +FROM amazoncorretto:11
Потому что докер файл должен быть там, где мы что-то запускаем. В нашем случае мы запускаем микросервис статистики. То есть этот докерфайл должен быть в одном модуле с этим микросервисом.

2023-02-16 03:41 UTC, sergeymamonov commented on stat-server/dto/src/main/java/com/example/dto/DtoApplication.java
> +public class DtoApplication {
В этом пакете должны быть класс или классы dto. Сейчас их здесь нет.

2023-02-16 03:41 UTC, sergeymamonov commented on stat-server/src/main/java/com/example/statserver/service/StatRepository.java
> +
Не исправлено.

2023-02-16 03:41 UTC, sergeymamonov commented on stat-server/src/main/java/com/example/statserver/service/StatServiceImpl.java
> +            int hitCount = listWithoutDuplicates.size();
Тогда проще в 55 строке сразу добавлять объекты не в массив, а во множество. Множество автоматом будет фильтровать дубликаты.

2023-02-16 03:46 UTC, sergeymamonov requested changes
В модуле статистики нужно сделать три подмодуля с помниками. У этих помников будет родительский помник, в вашем случае это будет помник stats_server. А в помнике stats_server указать три этих подмодуля.
Папку src из stats_server нужно выделить в модуль, как это сделано с client и dto.
Если тесты писать не собираетесь, то папки с тестами лучше удалить.

2023-02-16 03:46 UTC, sergeymamonov commented on stat-server/src/main/java/com/example/statserver/service/StatServiceImpl.java
> +        List<ViewStats> uniqueDataList = viewStatsSortFiltred.stream()
Можно сразу вернуть результат стрима, без создания промежуточной переменной uniqueDataList.

2023-02-16 20:12 UTC, sergeymamonov requested changes

2023-02-16 20:12 UTC, sergeymamonov commented on stat-server/pom.xml
> +    <dependencies>
В родительском помнике не должно быть никаких зависимостей. Все зависимости должны быть в дочерних помниках. Указание зависимостей в родитеском помнике связывает модули. А вся история с модулями, помниками как раз и нужна, чтобы разделить разные блоки кода и сделать их наименее зависимыми друг от друга.

2023-02-16 20:12 UTC, sergeymamonov commented on stat-server/stat-client/src/main/java/client/EventClient.java
> +    public void createHit(HttpServletRequest request) {
В контроллере два метода, а здесь, в клиенте, - один. Нужно дописать второй метод.

2023-02-17 12:16 UTC, sergeymamonov approved these changes

2023-02-17 12:16 UTC, sergeymamonov commented on stat-server/stat-src/src/main/java/com/example/statserver/service/StatServiceImpl.java
> +        if (Boolean.TRUE.equals(unique)) {
Можно проще if (unique) {...

2023-02-17 14:39 UTC, merged