Main svc
89219339769/java-explore-with-me pull request #3
Opened 2023-02-27 10:16 UTC by 89219339769

2023-02-28 13:19 UTC, sergeymamonov requested changes
Не нужно создавать лишние переменные, когда можно вернуть сразу результат вычисления выражения.
Посмотрите про разницу сравнения через  == и через equals(). Сейчас много мест, где используется ==, хотя должен использоваться equals(). Можно воспользоваться глобальным поиском по проекту, для нахождения всех мест. И equals нужно вызывать у константы, а не у объекта, объект может быть равным нуллу, и тогда будет NPE.

2023-02-28 13:19 UTC, sergeymamonov commented on main-server/src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS users (
Рекомендую сделать более аккуратное форматирование. Смотрите, для следующей таблицы уже другое форматирование. Лучше сделать везде единообразно.

2023-02-28 13:19 UTC, sergeymamonov commented on main-server/src/main/java/com/example/mainserver/category/controller/CategoryControllerAdmin.java
> +        if (category.getName() == null) {
Валидацию лучше перенести в сервис.

2023-02-28 13:19 UTC, sergeymamonov commented on main-server/src/main/java/com/example/mainserver/category/service/CategoryServiceImpl.java
> +        List<Category> categoryList = categoryPage.getContent();
Можно сразу вернуть результат вычисления выражения.

2023-02-28 13:19 UTC, sergeymamonov commented on main-server/src/main/java/com/example/mainserver/category/service/CategoryServiceImpl.java
> +        Category category = categoryRepository.findById(catId)
Аналогично, сразу возвращаем результат.

2023-02-28 13:19 UTC, sergeymamonov commented on main-server/src/main/java/com/example/mainserver/compilation/controller/CompilationControllerAdmin.java
> +        httpResponse.setStatus(201);
Лучше использовать не число, а константу из какой-нибудь библиотеки. Статусы есть в нескольких библиотеках.

2023-02-28 13:19 UTC, sergeymamonov commented on main-server/src/main/java/com/example/mainserver/compilation/controller/CompilationControllerAdmin.java
> +        CompilationDtoShort compilationDtoShort = compilationService.createCompilation(compilationDto);
Возвращаем сразу результат.

2023-02-28 13:19 UTC, sergeymamonov commented on main-server/src/main/java/com/example/mainserver/compilation/controller/CompilationControllerAdmin.java
> +//
Не оставляйте никакого закомментированного кода.

2023-02-28 13:19 UTC, sergeymamonov commented on main-server/src/main/java/com/example/mainserver/compilation/CompilationServiceImpl.java
> +        CompilationDtoShort compilationDtoShort = compilationMapper.toCompilationDtoShort(compilation);
Сразу возращайте.

2023-02-28 13:19 UTC, sergeymamonov commented on main-server/src/main/java/com/example/mainserver/compilation/CompilationServiceImpl.java
> +        CompilationDtoShort compilationDtoShort = compilationMapper.toCompilationDtoShort(compilation);
Сразу возращайте.

2023-02-28 13:19 UTC, sergeymamonov commented on main-server/src/main/java/com/example/mainserver/event/EventServiceImpl.java
> +        if (event.getState() == PUBLISHED) {
Во-первых, equals() нужно использовать, а во-вторых, использовать так, чтобы не было NPE, PUBLISHED.equals(event.getState())

предварительно проверив, что event.getState() != null

2023-02-28 13:19 UTC, sergeymamonov commented on main-server/src/main/java/com/example/mainserver/event/EventServiceImpl.java
> +        if (event == null)
В строке 149 выполняется event.getState(). Поэтому если проверять на нулл, то раньше

2023-02-28 13:19 UTC, sergeymamonov commented on main-server/src/main/java/com/example/mainserver/participation/controller/ParticipationControllerUser.java
> +    public ParticipationControllerUser(ParticipationServiceImpl participationService) {
Можно заменить на аннотацию Lombok.

2023-02-28 13:19 UTC, sergeymamonov commented on main-server/src/main/java/com/example/mainserver/participation/model/ParticipationChangeStatus.java
> +    public ParticipationChangeStatus(List<Integer> requestIds, StatusRequest statusRequest) {
Можно заменить на аннотацию Lombok.

2023-02-28 13:19 UTC, sergeymamonov commented on main-server/src/main/java/com/example/mainserver/participation/model/ParticipationChangeStatus.java
> +@Builder
Аннотации к классу, а не оставлять их в воздухе.

2023-02-28 13:19 UTC, sergeymamonov commented on main-server/src/main/java/com/example/mainserver/participation/model/ParticipationMapper.java
> +//    public static Request toRequest(Event event, User requester) {
Закомментированный код

2023-02-28 13:19 UTC, sergeymamonov commented on main-server/src/main/java/com/example/mainserver/participation/ParticipationService.java
> +    public ParticipationDto createParticipationRequest(Long userId, Long eventId);
В интерфейсе и так все методы публичные. Явно указывать не нужно

2023-02-28 13:19 UTC, sergeymamonov commented on main-server/src/main/java/com/example/mainserver/participation/ParticipationServiceImpl.java
> +            Participation participation = participationRepository.findById(Long.valueOf(participationId))
Не нужно делать запросы к БД в цикле. Плюс ниже

2023-02-28 13:19 UTC, sergeymamonov commented on main-server/src/main/java/com/example/mainserver/participation/ParticipationServiceImpl.java
> +        ParticipationListDto participationListDto = ParticipationListDto
Можно вернуть сразу

2023-02-28 13:19 UTC, sergeymamonov commented on main-server/src/main/java/com/example/mainserver/statisticClient/BaseClient.java
>  package com.example.mainserver.statisticClient;
Неверное наименование пакета. Этого пакет в главном модуле быть не должно. Клиент должен быть в модуле статистики. И именно клиентом из модуля статистики и необходимо пользоваться в главном сервисе.

2023-02-28 18:54 UTC, 89219339769 commented on main-server/src/main/java/com/example/mainserver/category/controller/CategoryControllerAdmin.java
> +        if (category.getName() == null) {
исправил

2023-02-28 18:55 UTC, 89219339769 commented on main-server/src/main/java/com/example/mainserver/category/service/CategoryServiceImpl.java
> +        List<Category> categoryList = categoryPage.getContent();
исправил

2023-02-28 18:56 UTC, 89219339769 commented on main-server/src/main/java/com/example/mainserver/category/service/CategoryServiceImpl.java
> +        Category category = categoryRepository.findById(catId)
исправил

2023-02-28 18:59 UTC, 89219339769 commented on main-server/src/main/java/com/example/mainserver/compilation/controller/CompilationControllerAdmin.java
> +        httpResponse.setStatus(201);
исправил

2023-02-28 19:10 UTC, 89219339769 commented on main-server/src/main/java/com/example/mainserver/participation/model/ParticipationMapper.java
> +//    public static Request toRequest(Event event, User requester) {
исправил

2023-02-28 19:10 UTC, 89219339769 commented on main-server/src/main/java/com/example/mainserver/participation/ParticipationService.java
> +    public ParticipationDto createParticipationRequest(Long userId, Long eventId);
исправил

2023-02-28 19:11 UTC, 89219339769 commented on main-server/src/main/java/com/example/mainserver/participation/ParticipationServiceImpl.java
> +            Participation participation = participationRepository.findById(Long.valueOf(participationId))
исправил

2023-02-28 19:11 UTC, 89219339769 commented on main-server/src/main/java/com/example/mainserver/participation/ParticipationServiceImpl.java
> +        ParticipationListDto participationListDto = ParticipationListDto
исправил

2023-02-28 19:12 UTC, 89219339769 commented on main-server/src/main/java/com/example/mainserver/statisticClient/BaseClient.java
>  package com.example.mainserver.statisticClient;
исправил

2023-03-01 08:17 UTC, 89219339769 commented on main-server/src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS users (
исправил

2023-03-01 11:38 UTC, sergeymamonov approved these changes
Устранены не все замечания. Посмотрите, возможно, они свернуты в ленте гихаба. Потому что часть замечаний без ваших ответов, и эти замечания не устранены. Клиент переделать к следующей сдаче.

2023-03-01 12:34 UTC, merged